from tkinter import *
import fif as ff
import pot as pt
def tot():
    s=int(e0.get())
    q=int(e1.get())
    r=int(e2.get())
    t=int(e3.get())
    y=int(e4.get())
    u=int(e5.get())
    n=[[s,q,r,t,y,u]]
    m=ff.lr.predict(n)
    p="ovr="+str(int(m))
    h=[[s,m,q,r,t,y,u]]
    i=pt.lr.predict(h)
    l="pot="+str(int(i))
    diso.config(text=p)
    disp.config(text=l)


r=Tk()
age=Label(r,text="age")
e0=Entry(r)
div=Label(r,text="diving")
e1=Entry(r)
han=Label(r,text="handling")
e2=Entry(r)
kik=Label(r,text="kicking")
e3=Entry(r)
pos=Label(r,text="position")
e4=Entry(r)
ref=Label(r,text="reflexes")
e5=Entry(r)
diso=Label(r,text="")
disp=Label(r,text="")
age.grid(row=0)
div.grid(row=1)
han.grid(row=2)
kik.grid(row=3)
pos.grid(row=4)
ref.grid(row=5)
e0.grid(row=0,column=1)
e1.grid(row=1,column=1)
e2.grid(row=2,column=1)
e3.grid(row=3,column=1)
e4.grid(row=4,column=1)
e5.grid(row=5,column=1)
b=Button(r,text="enter",command=tot)
s=Button(r,text="exit",command=exit)
s.grid(row=6,column=1)
diso.grid(row=7)
disp.grid(row=8)
b.grid()
r.mainloop()
